id: A1605FE5E
title: Calling the Guru From Afar
type: translation
pechas:
- I940AA554
- I4A07873C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:35:38.744587
  last_modified_at: 2023-01-04 11:35:38.744592
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I940AA554/3448: 7B24
  I4A07873C/0AD0: 7B24
